// import {Inter} from "next/font/google";
// import "./globals.css";
// import { ThemeProvider } from "@/components/theme-provider";
// import Header from "@/components/Header";
// import { ClerkProvider } from "@clerk/clerk-react";

// const inter=Inter({
//   subsets: ["latin"],})

// export const metadata = {
//   title: "AI Career Coach",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <ClerkProvider>
      
//     <html lang="en" className="dark" suppressHydrationWarning>
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//         >
//         <ThemeProvider
//           attribute="class"
//           defaultTheme="dark"
//           enableSystem
//           disableTransitionOnChange
//           >
//           {/* Header */}
//           <Header/>
//           <main className="min-h-screen">{children}</main>

//           {/* Footer */}
//           <footer className="bg-muted/50 py-12">
//             <div className="container mx-auto px-4 text-center text-gray-200">
//               <p>Made with 💗 by Shwetanshu</p>
//             </div>
//           </footer>
//         </ThemeProvider>
//       </body>
//     </html>
//           </ClerkProvider>
//   );
// }


import "./globals.css";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs"; // ✅ Correct package
import { ThemeProvider } from "@/components/theme-provider";
import Header from "@/components/Header";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata = {
  title: "AI Career Coach",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider appearance={{
      baseTheme: "dark",
    }}>
      <html lang="en" className="dark" suppressHydrationWarning>
        <body className={`${inter.variable} antialiased`}>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <Header />
            <main className="min-h-screen">{children}</main>
            <footer className="bg-muted/50 py-12">
              <div className="container mx-auto px-4 text-center text-gray-200">
                <p>Made with 💗 by Shwetanshu</p>
              </div>
            </footer>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}

